apiVersion: v1
kind: Service
metadata:
  name: netflix-app
  labels:
    app: netflix-app
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: metrics
      port: 9100         # Port exposé sur le service
      targetPort: 9100   # Port sur lequel l'application écoute
      nodePort: 30010    # Choisissez un port valide entre 30000-32767
  selector:
    app: netflix-app
