apiVersion: v1
kind: Service
metadata:
  name: netflix-app
  labels:
    app: netflix-app
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: metrics
      port: 9100         # Port exposé par le LoadBalancer
      targetPort: 9100   # Port sur lequel l'application écoute
  selector:
    app: netflix-app
